name: CI/CD - Insecure Node App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: 🧪 Ejecutar tests automatizados
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🧪 Ejecutar tests
        run: npm test

  lint:
    name: 🧹 Análisis de estilo con ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🔍 Ejecutar ESLint
        run: npx eslint .

  audit:
    name: 🔐 Análisis de vulnerabilidades en dependencias
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🔎 Ejecutar npm audit
        uses: oke-py/npm-audit-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          audit_level: low

  secrets:
    name: 🕵️ Escaneo de secretos expuestos
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🕵️ Ejecutar GitLeaks
        uses: gitleaks/gitleaks-action@v2
