name: Security Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-security-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.x"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar test
        run: npm test

      - name: Analizar dependencias
        run: npm audit
        continue-on-error: true

      - name: Buscar secrets expuestos
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ejecutar linter
        run: npm run lint
