name: Security Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: verificar repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.x"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar test
        run: npm test
        continue-on-error: true
      - name: Ejecutar linter
        run: npm run lint
        continue-on-error: true

  security-scans:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Verificar repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.x"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Analizar dependencias
        run: npm audit
        continue-on-error: true

      - name: Buscar secrets expuestos
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  semgrep-scan:
    needs: build-and-test
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:latest
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Verificar repositorio
        uses: actions/checkout@v4

      - name: Escanear código con Semgrep
        run: semgrep --config auto --sarif --output semgrep.sarif 2>/dev/null || true
        continue-on-error: true

      - name: Subir archivo SARIF a GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep-sast
